Add additional information on requirements in INSTALL.md
and improve formating.

Why:
This may help people prevent or resolve following issues
when running `make bootstrap SCHEME=chez`

- missing clang
```
make: clang: Command not found
make[1]: Entering directory 'support/c'
make[1]: clang: Command not found
```
- missing Chez thread support
```
Compiling idris2_app/idris2-boot.ss with output to idris2_app/idris2-boot.so
Exception: attempt to reference unbound identifier
make-thread-parameter at line 171, char 30 of idris2_app/idris2-boot.ss
```